/*jslint es6*/
/*jslint browser: true*/

//quiz ids are generated by require('crypto').randomBytes(16).toString('hex') with node.js
//quiz answers are stored in browser because results don't actually matter
//ugly solution for attempt number- store in custom data attribute
/**
 *
 * @param {string} id - unique quiz ID
 * @param {HTMLElement} button - button html element
 */

function runQuiz(id, button) {
    var answer = document.getElementById(id).getAttribute("data-answer");
    var selected = document.querySelector(`input[name="${id}-radio"]:checked`);
    if (selected.value === answer) {
        document.getElementsByName(`${id}-radio`).forEach((box) => (box.disabled = true));
        button.setAttribute(
            "data-attempts",
            Number(button.getAttribute("data-attempts")) + 1
        );
        button.disabled = true;
        selected.parentElement.style.color = "#0f0";
        if (button.getAttribute("data-attempts") === "1") {
            button.innerHTML = "correct on first try";
            button.style.color = "#0f0";
        } else if (button.getAttribute("data-attempts") === "4") {
            button.innerHTML = "failed";
            button.style.color = "#f00";
        } else {
            button.innerHTML = "correct in " + button.getAttribute("data-attempts") + " tries";
            button.style.color = "#ff0";
        }
    } else {
        button.setAttribute(
            "data-attempts",
            Number(button.getAttribute("data-attempts")) + 1
        );
        selected.parentElement.style.color = "#f00";
        selected.disabled = "true";
    }
}

//to add: service worker for ability to access completely offline.